apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: secrets-lister
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: nginx-landing-volume
        configMap:
          name: nginx-landing
      containers:
      - name: my-container
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          apk add --no-cache git
          git clone https://github.com/VSharapov/k8s-ssl-updater.git
          cd k8s-ssl-updater
          chmod +x alpine_setup.sh
          ./alpine_setup.sh
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 32Mi
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-landing-volume
          mountPath: /usr/share/nginx/html/k8s-ssl-updater/index.html
          subPath: index.html
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d
        - name: nginx-landing-volume
          mountPath: /usr/share/nginx/html/k8s-ssl-updater