apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-landing
data:
  index.html: |
    <a href="./upload/"> First upload key files here </a> <br>
    <a href="./cli/"   > ...then process them        </a>
    